mathvision:
  metadata:
    version: 1
  name: mathvision
  competency: vision
  task_modality: vision
  dataloader_file: seahelm_tasks/vision/mathvision/mathvision_dataloader.py
  dataloader_class: MathVisionDataloader
  metric_file: seahelm_tasks/vision/mathvision/mathvision_metric.py
  metric_class: MathVisionJudgeMetric
  metric: accuracy_score
  use_judges: true
  judge:
    judge_model_name: openai/gpt-oss-120b
    judge_model_type: vllm
    judge_init_args:
      tensor_parallel_size: auto
      async_scheduling: true
      load_format: instanttensor
    judge_generation_kwargs:
      max_tokens: 65536
      reasoning_effort: high
    judge_prompts:
      system_prompt: ""
      criteria_prompt: |-
        Assess whether the following CANDIDATE ANSWER is CORRECT or INCORRECT.
        For the CANDIDATE ANSWER to be correct, it must be consistent with the OFFICIAL ANSWER.

        The question, for reference only: {question}
        The OFFICIAL ANSWER: {official_answer}
        CANDIDATE ANSWER TO ASSESS: {candidate_answer}

        Reply only with CORRECT or INCORRECT.
  fewshot_num_examples:
    instruct: 0
    base: # no fewshot examples
  languages:
    en:
      filepath: MathLLMs/MathVision
      max_tokens: 4096
      prompt_template:
        preamble: ""
        task_template: |-
          Please first solve the problem step by step, then put your final answer or a single letter (if it is a multiple choice question) in one "\boxed{{}}".

          {question}{options}
        answer_template: ""
        answer_tag: "\\boxed{"

mathvision_mini:
  metadata:
    version: 1
  name: mathvision_mini
  competency: ${mathvision.competency}
  task_modality: ${mathvision.task_modality}
  dataloader_file: ${mathvision.dataloader_file}
  dataloader_class: ${mathvision.dataloader_class}
  metric_file: ${mathvision.metric_file}
  metric_class: ${mathvision.metric_class}
  metric: ${mathvision.metric}
  use_judges: ${mathvision.use_judges}
  judge: ${mathvision.judge}
  fewshot_num_examples: ${mathvision.fewshot_num_examples}
  languages: ${mathvision.languages}
