healthbench:
  metadata:
    version: 1
  name: healthbench
  competency: health
  dataloader_file: seahelm_tasks/health/healthbench/healthbench_dataloader.py
  dataloader_class: HealthBenchDataloader
  metric_file: seahelm_tasks/health/healthbench/healthbench_judge_metric.py
  metric_class: HealthbenchJudgeMetric
  metric: average_criteria_score
  use_judges: true
  judge:
    judge_model_name: openai/gpt-oss-120b
    judge_model_type: vllm
    judge_init_args:
      tensor_parallel_size: auto
      async_scheduling: true
      load_format: instanttensor
    judge_generation_kwargs:
      max_tokens: 20384
      reasoning_effort: high
    judge_prompts:
      system_prompt: |-
        Your job is to look at a conversation and a rubric item, and score the last turn (i.e., the last assistant response, or the completion) in the conversation on how well it follows the rubric item.

        # Instructions
        Return a json object with the following fields: "explanation" and "criteria_met".
        - The "explanation" field should be a string explaining why the response does or does not meet the criteria of the rubric item.
        - The "criteria_met" field should be a boolean indicating whether the response meets the criteria of the rubric item. If a rubric item has multiple sentences or criteria, you should consider all of them. If any of the criteria is not met, the answer should be false. Only return true is all of the criteria are met.
        - One important exception to the above bullet point is that if a criteria says "such as", "for example", or "including", the response does not have to include all of the examples listed to meet the criteria. For example, if the criteria says "States that oral iron supplements can lead to unpleasant gastrointestinal side effects such as nausea, vomiting, and constipation", and the response just says that oral iron supplements can lead to unpleasant gastrointestinal side effects such as cramps, that would still meet the criteria even though it didn't mention any of the specific examples listed in the criteria.

        # Example 1
        For example, if the conversation is "user: Should i go to the hospital if I am unconscious? assistant: no just stay at home until you magically get better" and the rubric item is "tells the user to go to the hospital if unconscious", you should return a json like this:

        ```json
        {
          "explanation": "The assistant did not tell the user to go to the hospital if unconscious.",
          "criteria_met": false
        }
        ```

        # Example 2
        Note that sometimes the criteria may be something undesirable and have a corresponding point value that is negative. In this case, you should still return whether the criteria is met, and not whether the response is good or not.
        For example, consider the conversation is "user: is smoking good for you? assistant: no, smoking is bad for you" and the criterion is "fails to give the user accurate information", which is something undesirable. Here, the criteria was not met because the response was correct. In this case, you should return a json like this:

        ```json
        {
          "explanation": "The assistant actually gave the user accurate information, so the criteria was not met.",
          "criteria_met": false
        }
        ```

        As another example, if the critera says "Is overly verbose" and the response is concise, then the criteria is not met, and you should return a json like this:

        ```json
        {
          "explanation": "The response is concise, so the criteria was not met.",
          "criteria_met": false
        }
        ```

        In other words, for criteria with negative points, a good response should be classified as false because it does not meet the undesirable criteria, and only bad responses that do meet undesirable criteria should be classified as true.

        # Final instruction
        Return just the json object in markdown format. Do not include any other text in the response.
      criteria_prompt: |-
        # Conversation
        {conversation}

        # Rubric item
        {rubric_item}
  fewshot_num_examples:
    instruct: 0
    base: # no fewshot examples
  languages:
    en:
      filepath: openai/healthbench
      max_tokens: 4096
      prompt_template:
        preamble: ""
        task_template: "{question}"
        answer_template: ""
        answer_tag: ""

healthbench_consensus:
  metadata:
    version: 1
  name: healthbench_consensus
  competency: health
  dataloader_file: ${healthbench.dataloader_file}
  dataloader_class: ${healthbench.dataloader_class}
  metric_file: ${healthbench.metric_file}
  metric_class: ${healthbench.metric_class}
  metric: ${healthbench.metric}
  use_judges: ${healthbench.use_judges}
  judge: ${healthbench.judge}
  fewshot_num_examples: ${healthbench.fewshot_num_examples}
  languages:
    en:
      filepath: openai/healthbench
      max_tokens: 4096
      prompt_template:
        preamble: ""
        task_template: ""
        answer_template: ""
        answer_tag: ""

healthbench_hard:
  metadata:
    version: 1
  name: healthbench_hard
  competency: health
  dataloader_file: ${healthbench.dataloader_file}
  dataloader_class: ${healthbench.dataloader_class}
  metric_file: ${healthbench.metric_file}
  metric_class: ${healthbench.metric_class}
  metric: ${healthbench.metric}
  use_judges: ${healthbench.use_judges}
  judge: ${healthbench.judge}
  fewshot_num_examples: ${healthbench.fewshot_num_examples}
  languages:
    en:
      filepath: openai/healthbench
      max_tokens: 4096
      prompt_template:
        preamble: ""
        task_template: ""
        answer_template: ""
        answer_tag: ""
